version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d blogdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: my_springboot_app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: blogdb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: