version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  tomcat:
    image: tomcat:10.1-jre21
    container_name: my_tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./target/my-blog-back.war:/usr/local/tomcat/webapps/ROOT.war
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: usersdb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: