db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:usersdb}
db.username=${POSTGRES_USER:sa}
db.password=${POSTGRES_PASSWORD:sa}

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update