CREATE TABLE IF NOT EXISTS posts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(256) NOT NULL,
    text           TEXT         NOT NULL,
    tags           TEXT,
    likes_count    INTEGER      NOT NULL DEFAULT 0,
    comments_count INTEGER      NOT NULL DEFAULT 0,
    image          BYTEA
    );

INSERT INTO posts (title, text, tags, likes_count, comments_count)
SELECT 'Название поста 1', 'Текст поста в формате Markdown...', '["tag_1", "tag_2"]', 5, 2
    WHERE NOT EXISTS (SELECT 1 FROM posts LIMIT 1);

INSERT INTO posts (title, text, tags, likes_count, comments_count)
SELECT 'Второй пост', 'Текст второго поста...', '["tag_3"]', 2, 1
    WHERE NOT EXISTS (SELECT 1 FROM posts WHERE id = 2);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGSERIAL PRIMARY KEY,
    text    TEXT    NOT NULL,
    post_id BIGINT  NOT NULL REFERENCES posts (id) ON DELETE CASCADE
    );

INSERT INTO comments (text, post_id)
SELECT 'Комментарий к посту 1', 1
    WHERE NOT EXISTS (SELECT 1 FROM comments WHERE post_id = 1 LIMIT 1);

INSERT INTO comments (text, post_id)
SELECT 'Ещё один комментарий к посту 1', 1
    WHERE NOT EXISTS (SELECT 1 FROM comments WHERE post_id = 1 AND text = 'Ещё один комментарий к посту 1');

INSERT INTO comments (text, post_id)
SELECT 'Комментарий ко второму посту', 2
    WHERE NOT EXISTS (SELECT 1 FROM comments WHERE post_id = 2 LIMIT 1);